shellEmulator: true

trustPolicy: no-downgrade

allowBuilds:
  esbuild: false
  simple-git-hooks: true

trustPolicyExclude:
  - semver@6.3.1
packages:
  - playground
  - examples/*

overrides:
  forges: 'workspace:*'
